Test/modal unit tests
cse112-sp22-group4/Electric-Pomato pull request #102
Opened 2022-05-13 23:01 UTC by HarrisSteven

Unit tests for the recent additions of the Settings and Info modals.  The tests include basic checks to ensure the styling of the modals updates to show/hide the modal when they are opened/closed.  For the settings, it also checks that local storage and the dropdown values are properly updated when the user saves different timing preferences. 

I also created a new constants file to save the default timer settings instead of having magic numbers around different files.

2022-05-13 23:42 UTC, LJMNZS approved these changes

2022-05-14 00:43 UTC, alanlwang1 requested changes
Looks good, see comment

2022-05-14 00:43 UTC, alanlwang1 commented on source/__tests__/SettingsModal.test.js
> +// Initialize the DOM with a StatsModal element
Update this comment to be correct

2022-05-14 01:38 UTC, HarrisSteven commented on source/__tests__/SettingsModal.test.js
> +// Initialize the DOM with a StatsModal element
oops

2022-05-14 01:43 UTC, alanlwang1 approved these changes

2022-05-14 01:59 UTC, merged

2022-05-14 02:05 UTC, xingyuzzzhu approved these changes