Enhancement / PWA updated
cse112-sp22-group4/Electric-Pomato pull request #107
Opened 2022-05-14 07:11 UTC by 46chris

Had to recreate branch because I fucked up the other's commit history and the workflows weren't running

2022-05-14 19:54 UTC, LJMNZS submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/47438076/168446286-461e1bdf-68b9-4e8a-abe9-d5ab26fee394.png)
I see you added the manifest, but Chrome's PWA check can't seem to fetch it. 
[https://stackoverflow.com/questions/62722853/pwa-manifest-is-there-but-chrome-says-no-manifest-found](https://stackoverflow.com/questions/62722853/pwa-manifest-is-there-but-chrome-says-no-manifest-found)
This says the manifest should be able to be seen under application/manifest, but it's not showing up there, so I think you might have to register it
![image](https://user-images.githubusercontent.com/47438076/168446430-f4baf06c-e002-465c-8a60-487a4af1648b.png)
From this it looks like the manifest is missing the prefer_related_applications property

2022-05-15 09:40 UTC, markbussard requested changes

2022-05-15 09:40 UTC, markbussard commented on source/serviceWorker.js
> +});
So, this isn't going to work properly due to the fact that we are using parcel to compile and bundle our app. Thus, none of these files will actually exist in the build with these pathnames

Parcel has a plugin for this via: [parceljs-service-workers](https://parceljs.org/languages/javascript/#service-workers)

Just using the code snippet they provided seemed to work for me.

2022-05-15 09:40 UTC, markbussard commented on source/manifest.json
> +        }
When I was running this locally, I seemed to be getting errors with the src paths for these icons. It seems to work for me when removing the './' so -> img/pomatoPNG.png for example.

2022-05-15 09:40 UTC, markbussard commented on source/serviceWorker.js
> +});
Also, the fetch event listener will stay as is.

2022-05-15 09:43 UTC, markbussard commented
Let me know if you have any questions / need help. Also, I believe we will need a separate manifests file for app and technicall done, since these are different pages and will require a different 'start_url' property?

2022-05-16 08:04 UTC, markbussard approved these changes
There's still a couple minor issues noted per the lighthouse report that we could add in to complete the PWA optimization criteria.

However, the app appears to work just fine in offline mode, which is the important part for the demo. So, I'd say this is good to go as long as we get some more reviews / approvals from people to ensure no obvious issues, and we can worry about the other items from the lighthouse report later.

2022-05-16 16:54 UTC, merged