Change behavior on resuming session
cse112-sp22-group4/Electric-Pomato pull request #136
Opened 2022-05-21 20:00 UTC by alanlwang1

Closes #135 
Changed behavior on resuming session to always start at a Pomo session, regardless of what session the user left at 
Added new field `CurrentPomos` to backend to track whether the user is on a short or long break 
`CurrentPomos` will also reset to 0 when the user resumes the session, so the user's progress towards a long break is also reset

2022-05-21 22:29 UTC, xingyuzzzhu approved these changes
lgtm

2022-05-22 03:42 UTC, LJMNZS approved these changes

2022-05-22 04:32 UTC, HarrisSteven commented
CurrentPomos also resets to 0 on refresh. This means if you are on the break and refresh it will take you back to a pomo session. Is this the expected behavior?

2022-05-22 04:48 UTC, HarrisSteven requested changes

2022-05-22 04:48 UTC, HarrisSteven commented on source/js/backend.js
> +  localStorage.removeItem('CurrentPomos');
Can you add CurrentPomos to `removeAll` too just for completeness

2022-05-22 16:41 UTC, HarrisSteven commented on source/js/scripts/app.js
> +    // On resuming session, reset timer state and current pomos
Maybe we should reset these values in `StartButtons.js` when the user clicks the Resume My Session button so they won't get reset on a reload

2022-05-22 16:42 UTC, HarrisSteven commented on source/js/scripts/app.js
> +    backend.set('CurrentPomos', 0);
Maybe we should reset these values in `StartButtons.js` when the user clicks the Resume My Session button so they won't get reset on a reload

2022-05-22 19:08 UTC, HarrisSteven approved these changes

2022-05-22 19:14 UTC, merged